apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-world-node-express
  labels:
    app: hello-world-node-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-node-express
  template:
    metadata:
      labels:
        app: hello-world-node-express
    spec:
      containers:
        - name: hello-world-node-express
          image: IMAGE_NAME
          ports:
            - containerPort: CONTAINER_PORT
           