apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-world-node-express
  labels:
    app: hello-world-node-express
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world-node-express
  template:
    metadata:
      labels:
        app: hello-world-node-express
    spec:
      containers:
        - name: hello-world-node-express
          image: saviganga/ignitedotdev-node-express
          ports:
            - containerPort: 3000
          
           