name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the docker image
      id: build
      run: |
        COMMIT_HASH=$(git rev-parse HEAD)

        # Get the previous commit hash (if available)
        PREVIOUS_COMMIT_HASH=$(git rev-parse HEAD^ 2>/dev/null || echo "")

        # Compare the current and previous commit hashes
        if [ "$COMMIT_HASH" != "$PREVIOUS_COMMIT_HASH" ]; then
          # Only build and tag the image if there are differences
          docker build . --file Dockerfile --tag ${{secrets.IMAGE_NAME}}:$COMMIT_HASH
        else
          echo "No code changes detected. Skipping image build."
        fi
      shell: bash

    - name: Docker push
      run: docker push ${{secrets.IMAGE_NAME}}:$COMMIT_HASH